spring:
  application:
    name: zr7
  sql:
    init:
      mode: never
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/coupons}
    username: ${DB_USERNAME:coupon_user}
    password: ${DB_PASSWORD:couponPass}
  # from assumption that our user has no permissions to use DDL, we need an separate user to do such things
  flyway:
    enabled: true
    user: ${FLYWAY_USER:coupon_db_owner}
    password: ${FLYWAY_PASSWORD:db_owner}
  #timeouts for RestClient used in geolocation
  http:
    client:
      connect-timeout: 3s
      read-timeout: 5s

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

geolocation:
  provider: ipapi
  cache:
    ttl: 10m
    max-size: 10000

coupon:
  exhaustion-cache:
    ttl: 30m
    max-size: 10000
  lookup-cache:
    ttl: 30m
    max-size: 10000

logging:
  level:
    org.flywaydb: info
    org.springframework.boot.autoconfigure.flyway: info
debug: false